version: '3.3'

services:
  app:
    image: amarmulyak/address_book:origin
    container_name: address_book
    restart: unless-stopped
    tty: true
    ports:
      - 3000:3000

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app